services:
  # 1. Base de données (MySQL)
  db:
    image: mysql:8.0
    container_name: bssahty-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bssahty_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - bssahty-network

  # 2. Backend PHP-FPM
  app:
    build:
      context: ./bssahtyApi
      dockerfile: docker/php/Dockerfile
    container_name: bssahty-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./bssahtyApi:/var/www
    depends_on:
      - db
    networks:
      - bssahty-network

  # 3. Serveur Web Nginx
  nginx:
    image: nginx:latest
    container_name: bssahty-nginx
    ports:
      - "8000:80"
    volumes:
      - ./bssahtyApi:/var/www
      - ./bssahtyApi/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bssahty-network

  # 4. Frontend Vue.js (Vite)
  front:
    build:
      context: ./bssahty-front
      dockerfile: Dockerfile
    container_name: bssahty-front
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./bssahty-front:/app
      - /app/node_modules
    depends_on:
      - nginx
    networks:
      - bssahty-network

networks:
  bssahty-network:
    driver: bridge

volumes:
  dbdata: